# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: 🧹 Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        task:
          - gh
          - sh
          - go
          - md
          - js
          - yml
    steps:
      - name: 🩺 Debug
        uses: raven-actions/debug@9dbdeb7eea607a7d73411895c65987e71d59a466 # v1.2.0

      - name: ⤵️ Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🚧 Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version

      - name: 🚧 Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: 🚧 Setup Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2.1.0
        with:
          repo-token: ${{ github.token }}

      - name: 🚧 Setup runtime (UV)
        run: task runtime:setup:uv
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 🔨 Setup tools
        run: task ${{ matrix.task }}:tools:lint
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 🌌 Ensure bin path
        if: runner.os == 'Linux'
        run: |
          INSTALL_PATH="$HOME/.local/bin"

          echo "$INSTALL_PATH" >> "${GITHUB_PATH}"
          export PATH="$INSTALL_PATH:$PATH"
        shell: bash

      - name: 🌌 Ensure bin path
        if: runner.os == 'Windows'
        run: |
          $INSTALL_PATH = "$env:USERPROFILE\.local\bin"
          $INSTALL_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          $env:PATH = "$INSTALL_PATH;$env:PATH"

          $INSTALL_PATH = "$env:LOCALAPPDATA\Microsoft\WinGet\Links"
          $INSTALL_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          $env:PATH = "$INSTALL_PATH;$env:PATH"

          $INSTALL_PATH = "$env:LOCALAPPDATA\Microsoft\WindowsApps"
          $INSTALL_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          $env:PATH = "$INSTALL_PATH;$env:PATH"
        shell: pwsh

      - name: ✔️ Run lint (${{ matrix.task }})
        run: task ${{ matrix.task }}:lint

      - name: 🔀 Check for differences
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        run: task diff -- "${{ matrix.task }}:lint"

  check-lint:
    if: always()
    name: 🧹 Check Lint
    needs: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: ✅ OK
        if: ${{ !(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
        run: exit 0
      - name: 🛑 Failure
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
